# Generated by Django 2.2.4 on 2019-08-21 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190820_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_name',
            new_name='user',
        ),
    ]
