# Generated by Django 2.2.4 on 2019-08-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryArticle',
        ),
        migrations.AlterModelOptions(
            name='categoryarticle',
            options={'ordering': ['-created'], 'verbose_name': 'categoría de artículo', 'verbose_name_plural': 'categorías de artículos'},
        ),
    ]
