# Generated by Django 2.2.4 on 2019-08-21 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=30, verbose_name='Monto Total de la Compra')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de Facturación')),
                ('status', models.CharField(choices=[('a', 'Activa'), ('d', 'Devuelta'), ('i', 'Inactiva')], max_length=1, verbose_name='Estado de la Factura')),
                ('address', models.ForeignKey(on_delete=None, to='core.Address', verbose_name='Dirección de Envio')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad del Artículo')),
                ('amount', models.FloatField(max_length=30, verbose_name='Monto por Cantidad de Artículo')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Article', verbose_name='Artículo a Comprar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'carrito de compra',
                'verbose_name_plural': 'carritos de compra',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('tc', 'Tarjeta de Crédito'), ('pp', 'Paypal')], max_length=2, verbose_name='Tipo de Pago')),
                ('transaction_code', models.CharField(max_length=20, verbose_name='Código de la Transacción')),
                ('status', models.CharField(choices=[('e', 'Exitosa'), ('f', 'Fallida')], max_length=1, verbose_name='Estado de la Transacción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'detalles de pago',
                'verbose_name_plural': 'detalles de pagos',
            },
        ),
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad del Artículo')),
                ('amount', models.FloatField(max_length=30, verbose_name='Monto por Cantidad de Artículo')),
                ('article', models.ForeignKey(on_delete=None, to='core.Article', verbose_name='Artículo Comprado')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bill', verbose_name='Id de la Factura')),
            ],
            options={
                'verbose_name': 'detalle de factura',
                'verbose_name_plural': 'detalles de facturas',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PaymentDetails', verbose_name='Detalles del Pago'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
