# Generated by Django 2.2.4 on 2019-08-21 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190821_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['code'], 'verbose_name': 'artículo', 'verbose_name_plural': 'artículos'},
        ),
        migrations.AddField(
            model_name='search',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.CategoryArticle', verbose_name='Categoria de Búsqueda'),
            preserve_default=False,
        ),
    ]
