# Generated by Django 2.2.4 on 2019-08-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190821_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CategoryArticle', verbose_name='Categoria de Búsqueda'),
        ),
    ]
