# Generated by Django 2.2.4 on 2019-08-22 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190822_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='id_session',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id de la Sesión'),
        ),
        migrations.AlterField(
            model_name='search',
            name='phrase',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Frase de Búsqueda'),
        ),
        migrations.AlterField(
            model_name='search',
            name='time',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Tiempo de Búsqueda'),
        ),
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
