# Generated by Django 2.2.4 on 2019-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190822_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('a', 'Activo'), ('c', 'Comprado'), ('e', 'Eliminado')], default='a', max_length=1, verbose_name='Estado del ítem en carrito'),
            preserve_default=False,
        ),
    ]
