# Generated by Django 2.2.4 on 2019-08-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190823_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='time',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de Búsqueda'),
        ),
    ]
