# Generated by Django 2.2.4 on 2019-08-24 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190823_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 23, 27, 25, 889164)),
        ),
    ]
