# Generated by Django 2.2.4 on 2019-08-25 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_last_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foto', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 18, 32, 19, 391071)),
        ),
    ]
