# Generated by Django 2.2.4 on 2019-08-25 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190825_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='foto/default.jpg', null=True, upload_to='foto', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 18, 38, 27, 791531)),
        ),
    ]
