# Generated by Django 2.2.4 on 2019-08-28 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190825_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 0, 33, 42, 938368)),
        ),
    ]
