# Generated by Django 2.2.4 on 2019-08-28 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190828_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 1, 49, 52, 407447)),
        ),
    ]
